on:
  schedule:
    #- cron: '*/30 * * * *'
    #- cron: '25 16 * * *'
jobs:
  test_schedule:
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    runs-on: windows-latest
    steps:
     - name: Check out
       uses: actions/checkout@v2
    
     - name: Set up Python
       uses: actions/setup-python@v2
       with: 
         python-version: '3.12'
     
     - name: Install the necessary packages
       run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

     - name: Authenticate to Google Cloud
       uses: google-github-actions/auth@v2
       with:
         service_account: 'auc-224@auctions-422114.iam.gserviceaccount.com'
         workload_identity_provider: 'projects/auctions-422114/locations/global/workloadIdentityPools/auctions_github_pool/providers/provd'
          
     - name: Run script
       run: python 1.py
          
     - name: Upload text file as artifact
       uses: actions/upload-artifact@v3
       with:
         name: logs-and-files
         path: |
           dd.txt
           logs
    
