on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  test_schedule:
    runs-on: windows-latest
    steps:
     - name: Check out
       uses: actions/checkout@v2
    
     - name: Set up Python
       uses: actions/setup-python@v2
       with: 
         python-version: '3.12'
     
     - name: Run script
       run: python 1.py

     - name: Upload text file as artifact
       uses: actions/upload-artifact@v3
       with:
         name: sample-text-file
         path: dd.txt
